public class Question_1 {
//    Kth Symbol row generated by replacing all elements of previous row
//    0 -> 0 1 & 1 -> 1 0
//    At nth row, find Kth Symbol?
    public static void main(String[] args) {
        int n=5,k=7;
        System.out.println("ans : "+find(n,k));
    }
    static int find(int n,int k){
        if(k==0){
            return 0;
        }
        int val = find(n-1,k/2);
        if(k%2==0){
            return val;
        }else{
            return val==0 ? 1 : 0;
        }
    }
}
